version: '3.9'
services:
  postgres:
    image: postgres
    volumes:
      - .:./app
    environment:
      - "${POSTGRES_USER}:${POSTGRES_USER}"
      - "${POSTGRES_PASSWORD}:${POSTGRES_PASSWORD}"
      - "${POSTGRES_DB}:${POSTGRES_DB}"
    ports:
      - "5432:5432"
  # api:
  #   build: .
  #   command: npm run start:prod
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     - PORT=${PORT}
  #     - JWT_SECRET=${JWT_SECRET}
  #   depends_on:
  #     - postgres

